services:
  app:
    container_name: app
    image: ghcr.io/agachot/next_ci_cd_2_06-2026:prod
    networks:
      - myapp

  postgres:
    container_name: postgres
    image: postgres:18-alpine3.24
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db:/var/lib/postgresql/18/docker'
    networks:
      - myapp

  redis:
    container_name: redis
    image: redis:8.8-alpine3.23
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=${REDIS_ARGS}
    restart: unless-stopped
    networks:
      - myapp

networks:
  myapp:
    driver: bridge # seul les services de ce cdocker compose peuvent communiquert entre eux

volumes:
  db:
  redis-data:
    driver: local