name: CI

on:
  pull_request:
    branches:
      - prod
  push:
    branches:
      - dev

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: install checkout
        uses: actions/checkout@v7

      - name: check version docker
        run: |
          docker -v
          docker compose up
      
